"""The experiment record: one row per run, written as the runs happen.

The full harness is Gate 5, but its column schema is needed now. Stage 4 alone
produces around 910 reproduction fits and 30 Arm A runs, doubling if the
polarity experiment runs alongside, so roughly two thousand rows. Fixing the
schema first means those rows land in `results/experiments.csv` complete,
rather than being re-run in November purely to record them properly.

Every number that appears in the paper must be traceable to one row, and every
figure must be generated by a script that reads this file. The commit hash is
recorded per row so that a result can be tied to the code that produced it.
"""

from __future__ import annotations

import csv
import subprocess
from dataclasses import asdict, dataclass, field, fields
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXPERIMENTS = ROOT / "results" / "experiments.csv"


def commit_hash() -> str:
    """Short hash of the code that produced a row, or 'dirty'/'unknown'."""
    try:
        head = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
        changed = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=no"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
        return f"{head}-dirty" if changed else head
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


@dataclass
class Run:
    """One experiment. Configuration first, then results, then provenance."""

    # What was run
    arm: str  # A, B, B2, C1, C1-scratch, C2, D, or reproduction
    backbone: str  # s or p
    polarity: str  # asis or flipped
    protocol: str  # activity, temporal, or papagei-9-3-3
    subject: int | str  # held-out subject, or the test triple for the reproduction

    # How much personal data it was given
    budget_minutes: float | None = None
    usable_minutes: float | None = None
    elapsed_minutes: float | None = None

    # What it cost per person
    trainable_parameters: int = 0
    stored_bytes: int = 0

    # What it scored
    mae: float | None = None
    rmse: float | None = None
    pearson: float | None = None
    n_test_windows: int | None = None

    # How it was configured
    alpha: float | None = None
    rank: int | None = None
    seed: int = 0
    hyperparameters: str = ""  # anything not worth its own column, as JSON

    # Where it came from
    commit: str = field(default_factory=commit_hash)
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds"))
    notes: str = ""


def append(runs: Run | list[Run], path: Path = EXPERIMENTS) -> int:
    """Append rows, writing the header if the file is new. Returns rows written."""
    rows = [runs] if isinstance(runs, Run) else list(runs)
    if not rows:
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [f.name for f in fields(Run)]
    exists = path.exists()
    with open(path, "a", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=header)
        if not exists:
            writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))
    return len(rows)


def load(path: Path = EXPERIMENTS) -> list[dict]:
    if not path.exists():
        return []
    with open(path, newline="") as handle:
        return list(csv.DictReader(handle))


if __name__ == "__main__":
    print("columns:")
    for f in fields(Run):
        print(f"  {f.name}")
    print(f"\ncommit: {commit_hash()}")
    print(f"rows currently recorded: {len(load()):,}")
